export const WEAKNESS_LIST = {
  backdoor: "后门",
  buffer_overflow: "缓冲区溢出",
  click_jacking: "点击劫持",
  cors: "跨域",
  crlf: "CRLF注入",
  cryptography_problem: "密码学问题",
  csrf: "CSRF",
  default_passord: "默认账户口令",
  deserialization: "反序列化漏洞",
  directory_traversal: "路径遍历",
  dos: "拒绝服务",
  double_free: "双重释放",
  enum: "枚举",
  file_delete: "文件删除",
  file_inclusion: "文件包含",
  file_upload: "文件上传",
  heap_overflow: "堆溢出",
  idor: "鉴权绕过",
  integer_overflow: "整数溢出",
  ldap_injection: "LDAP注入",
  leak: "敏感信息泄露",
  logical: "逻辑漏洞",
  memory_safety: "内存安全",
  other: "其他",
  out_of_bounds: "越界访问",
  command_injection: "远程命令执行",
  race_condition: "条件竞争",
  rce: "远程代码执行",
  readfile: "文件读取",
  rpo: "相对路径覆盖",
  sql_injection: "SQL注入",
  ssrf: "SSRF",
  ssti: "SSTI",
  stack_overflow: "栈溢出",
  type_confusion: "类型混淆",
  unauthorized_access: "未授权访问",
  uncontrolled_format_string: "格式化字符串",
  uninitialized_variable: "未初始化变量",
  unsafe_account: "账户认证体系漏洞",
  unsafe_config: "不安全的配置",
  url_redirection: "URL跳转",
  use_after_free: "释放后重引用",
  weak_password: "弱口令",
  writefile: "文件写入",
  xpath_injection: "XPath注入",
  xss: "XSS",
  xxe: "XXE",
};

export const SCORE_ENUMS = {
  AV: {
    label: "触发方式",
    N: 100,
    A: 75,
    L: 50,
    P: 25,
  },
  触发方式: {
    label: "AV",
    N: 100,
    A: 75,
    L: 50,
    P: 25,
  },
  AC: {
    label: "攻击难度",
    L: 100,
    H: 50,
  },
  攻击难度: {
    label: "AC",
    L: 100,
    H: 50,
  },
  PR: {
    label: "认证需求",
    N: 100,
    L: 66,
    H: 33,
  },
  认证需求: {
    label: "PR",
    N: 100,
    L: 66,
    H: 33,
  },
  UI: {
    label: "交互行为",
    N: 100,
    R: 50,
  },
  交互行为: {
    label: "UI",
    N: 100,
    R: 50,
  },
  S: {
    label: "影响范围",
    C: 100,
    U: 50,
  },
  影响范围: {
    label: "S",
    C: 100,
    U: 50,
  },
  C: {
    label: "机密性",
    H: 100,
    L: 66,
    N: 33,
  },
  机密性: {
    label: "C",
    H: 100,
    L: 66,
    N: 33,
  },
  I: {
    label: "完整性",
    H: 100,
    L: 66,
    N: 33,
  },
  完整性: {
    label: "I",
    H: 100,
    L: 66,
    N: 33,
  },
  A: {
    label: "可用性",
    H: 100,
    L: 66,
    N: 33,
  },
  可用性: {
    label: "A",
    H: 100,
    L: 66,
    N: 33,
  },
};

export const TEXT = {
  1: "雷池（SafeLine）下一代Web应用防火墙",
  2: "洞鉴（X-Ray）安全评估系统",
  4: "牧云（CloudWalker） 主机安全管理平台",
  5: "全悉（T-ANSWER）高级威胁分析预警系统",
  3: "云图（Cloud Atlas）攻击面管理运营平台",
  6: "谛听（D-Sensor） 伪装欺骗系统",
};
